<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd10e1615351b7c992de360e2e63971b4
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd10e1615351b7c992de360e2e63971b4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd10e1615351b7c992de360e2e63971b4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd10e1615351b7c992de360e2e63971b4::$classMap;

        }, null, ClassLoader::class);
    }
}
